use rocksdb::WriteBatch;
use serde_derive::{Deserialize, Serialize};

use crate::db::{db, MergeOperation, Table};

use super::ObjectRef;

#[derive(Debug, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Serialize, Deserialize)]
pub enum BookmarkType {
    /// A bookmark generated by the dependency from other entities in the database.
    Reference,
    /// A bookmark defined by the user.
    User,
}

#[derive(Debug, Clone)]
pub struct Bookmark {
    ty: BookmarkType,
    object: ObjectRef,
}

impl Bookmark {
    pub(crate) fn new(ty: BookmarkType, object: ObjectRef) -> Bookmark {
        Bookmark { ty, object }
    }

    fn key(&self) -> Vec<u8> {
        [
            self.object.hash().as_ref(),
            bincode::serialize(&self.ty)
                .expect("can serialize")
                .as_ref(),
        ]
        .concat()
    }

    pub fn is_marked(&self) -> Result<bool, crate::Error> {
        Ok(db().get_cf(Table::Bookmarks.get(), self.key())?.is_some())
    }

    pub fn mark_with(&self, batch: &mut WriteBatch) {
        let operation = match self.ty {
            BookmarkType::Reference => MergeOperation::Increment,
            BookmarkType::User => MergeOperation::Set,
        };

        batch.merge_cf(
            Table::Bookmarks.get(),
            self.key(),
            bincode::serialize(&operation).expect("can serialize"),
        )
    }

    pub fn mark(&self) -> Result<(), crate::Error> {
        let mut batch = WriteBatch::default();
        self.mark_with(&mut batch);
        db().write(batch)?;

        Ok(())
    }

    pub fn unmark_with(&self, batch: &mut WriteBatch) {
        let operation = match self.ty {
            BookmarkType::Reference => MergeOperation::Decrement,
            BookmarkType::User => MergeOperation::Clear,
        };

        batch.merge_cf(
            Table::Bookmarks.get(),
            self.key(),
            bincode::serialize(&operation).expect("can serialize"),
        )
    }

    pub fn unmark(&self) -> Result<(), crate::Error> {
        let mut batch = WriteBatch::default();
        self.unmark_with(&mut batch);
        db().write(batch)?;

        Ok(())
    }

    pub fn clear_with(&self, batch: &mut WriteBatch) {
        batch.delete_cf(Table::Bookmarks.get(), self.key())
    }
}
