[workspace]

members = [
    "common",
    "node",
    "hub",
    "cli",
    "proxy",
    "install/src/x86_64-pc-windows-gnu/node/samizdat-service",
]
resolver = "2"

[profile.release]

opt-level = "s"
lto = "fat"
