###
#
# Samizdat manifest for the `installation` folder.
#
###

[series]
# Here goes the public information of the series in this directory.

name = "get-samizdat"
public-key = "r0Km0HptEt6Fhosmy7qxaKxyDtwHkzi0-eYbt1WatdM"
# ttl = "1h"    # set a time-to-live different from the default


[debug]
# Same thing as the last section, but for debugging and testing purposes.

name = "get-samizdat-debug"
# ttl = "1h"


[build]
# Build instructions for this series.

base = "./dist"
run = "./install/build.sh 'aarch64-apple-darwin x86_64-unknown-linux-gnu'"
