#cloud-config

###
#
# Configuration for a Ubuntu VPS to be able to run a Samizdat Hub for the open
# Web.
#
###

package_update: true
package_upgrade: true
packages:
  - fish
  - certbot
runcmd:
  - chsh -s /usr/bin/fish
  - yes | ufw enable
  - ufw allow ssh
  - ufw allow http
  - ufw allow https
  - ufw allow 4511/udp
  - ufw allow 4512/udp
