[package]
name = "samizdat-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_once = "0.2.6"
base64-url = "1.4.13"
bytes = "1.1.0"
failure = "0.1.8"
failure_derive = "0.1.8"
futures = "0.3.21"
getrandom = "0.2.6"
http = "0.2.7"
lazy_static = "1.4.0"
log = "0.4.17"
log4rs = "1.1.1"
rocksdb = { version = "0.18.0", default-features = false, features = ["snappy"] }
serde = "1.0.137"
serde_derive = "1.0.137"
sha3 = "0.10.1"
structopt = "0.3.26"
tarpc = { version = "0.28.0", features = ["tokio1", "serde-transport", "tcp"] }
tokio = { version = "1.18.1", features = ["rt-multi-thread", "macros", "net", "time"] }
warp = { version = "0.3.2", default-features = false }
samizdat-common = { path = "../common" }
quinn = "0.8.2"
bincode = "1.3.3"
notify = "5.0.0-pre.15"
hyper = { version = "0.14.18", features = ["stream"] }
aes-gcm-siv = "0.10.3"
async-trait = "0.1.53"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
chrono = { version = "0.4.19", features = ["serde"] }
serde_json = "1.0.81"
humantime-serde = "1.1.1"
brotli = "3.3.4"
decorum = "0.3.1"
semver = "1.0.9"
rand = "0.7"
url = "2.2.2"
askama = { version = "0.11.1", features = ["serde-json"] }
strum = "0.24.0"
strum_macros = "0.24.0"
