[package]
name = "samizdat-common"
version = "0.1.0"
authors = ["Pedro B Arruda <parruda@artmend.com.br>"]
edition = "2021"

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "2.1.2"
log = "0.4.17"
log4rs = "1.1.1"
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros", "net", "time"] }
failure = "0.1.8"
failure_derive = "0.1.8"
rocksdb = { version = "0.19.0", default-features = false, features = [] }
futures = "0.3.24"
tarpc = { version = "0.30.0", features = ["tokio1", "serde-transport", "tcp"] }
base64-url = "1.4.13"
serde_derive = "1.0.144"
serde = { version = "1.0.144", features = ["rc"] }
tokio-util = "0.7.3"
bytes = "1.2.1"
bincode = "1.3.3"
tokio-stream = { version = "0.1.9", features = ["net"] }
sha3 = "0.10.2"
warp = { version = "0.3.2", default-features = false }
getrandom = "0.2.7"
quinn = "0.8.5"
rustls = { version = "0.20.6", default-features = false, features = ["quic", "dangerous_configuration"] }
webpki = "0.22.0"
rcgen = "0.9.3"
chrono = { version = "0.4.22", features = ["serde"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
aes-gcm-siv = "0.11.1"
anyhow = "1.0.63"
rustls-pemfile = "1.0.1"
typenum = "1.15.0"
