[package]
name = "samizdat-common"
version = "0.1.0"
authors = ["Pedro B Arruda <parruda@artmend.com.br>"]
edition = "2021"

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "2.0.0"
log = "0.4.14"
log4rs = "1.0.0"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros", "net", "time"] }
failure = "0.1.8"
failure_derive = "0.1.8"
rocksdb = { version = "0.18.0", default-features = false, features = [] }
futures = "0.3.21"
tarpc = { version = "0.27.2", features = ["tokio1", "serde-transport", "tcp"] }
base64-url = "1.4.10"
serde_derive = "1.0.136"
serde = { version = "1.0.136", features = ["rc"] }
tokio-util = "0.7.0"
bytes = "1.1.0"
bincode = "1.3.3"
tokio-stream = { version = "0.1.8", features = ["net"] }
sha3 = "0.10.0"
warp = { version = "0.3.2", default-features = false }
getrandom = "0.2.4"
quinn = "0.8.0"
rustls = { version = "0.20.3", default-features = false, features = ["quic", "dangerous_configuration"] }
webpki = "0.22.0"
rcgen = "0.9.1"
chrono = { version = "0.4.19", features = ["serde"] }
rand = "0.7.3"
rand_chacha = "0.2.2"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
aes-gcm-siv = "0.10.3"
anyhow = "1.0.53"
rustls-pemfile = "0.3.0"
