[package]
name = "samizdat-common"
version = "0.1.0"
authors = ["Pedro B Arruda <parruda@artmend.com.br>"]
edition = "2021"

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "22.10.26"
log = "0.4.17"
log4rs = "1.2.0"
tokio = { version = "1.23.0", features = ["rt-multi-thread", "macros", "net", "time"] }
failure = "0.1.8"
failure_derive = "0.1.8"
rocksdb = { version = "0.19.0", default-features = false, features = [] }
futures = "0.3.25"
tarpc = { version = "0.31.0", features = ["tokio1", "serde-transport", "tcp"] }
base64-url = "1.4.13"
serde_derive = "1.0.152"
serde = { version = "1.0.152", features = ["rc"] }
tokio-util = "0.7.4"
bytes = "1.3.0"
bincode = "1.3.3"
tokio-stream = { version = "0.1.11", features = ["net"] }
sha3 = "0.10.6"
warp = { version = "0.3.3", default-features = false }
getrandom = "0.2.8"
quinn = "0.9.3" # do NOT upgrade until quinn bugfix!
rustls = { version = "0.20.7", default-features = false, features = ["quic", "dangerous_configuration"] }
webpki = "0.22.0"
rcgen = "0.10.0"
chrono = { version = "0.4.23", features = ["serde"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
aes-gcm-siv = "0.11.1"
anyhow = "1.0.68"
rustls-pemfile = "1.0.1"
typenum = "1.16.0"
serde_json = "1.0.91"
