[package]
name = "samizdat-common"
version = "0.1.0"
authors = ["Pedro B Arruda <parruda@artmend.com.br>"]
edition = "2021"

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "2.1.2"
log = "0.4.17"
log4rs = "1.1.1"
tokio = { version = "1.18.1", features = ["rt-multi-thread", "macros", "net", "time"] }
failure = "0.1.8"
failure_derive = "0.1.8"
rocksdb = { version = "0.18.0", default-features = false, features = [] }
futures = "0.3.21"
tarpc = { version = "0.28.0", features = ["tokio1", "serde-transport", "tcp"] }
base64-url = "1.4.13"
serde_derive = "1.0.137"
serde = { version = "1.0.137", features = ["rc"] }
tokio-util = "0.7.1"
bytes = "1.1.0"
bincode = "1.3.3"
tokio-stream = { version = "0.1.8", features = ["net"] }
sha3 = "0.10.1"
warp = { version = "0.3.2", default-features = false }
getrandom = "0.2.6"
quinn = "0.8.2"
rustls = { version = "0.20.4", default-features = false, features = ["quic", "dangerous_configuration"] }
webpki = "0.22.0"
rcgen = "0.9.2"
chrono = { version = "0.4.19", features = ["serde"] }
rand = "0.7.0"
rand_chacha = "0.2.0"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
aes-gcm-siv = "0.10.3"
anyhow = "1.0.57"
rustls-pemfile = "1.0.0"
