[package]
name = "samizdat-common"
version = "0.1.0"
authors = ["Pedro B Arruda <parruda@artmend.com.br>"]
edition = "2018"

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "2.0.0"
log = "0.4.14"
log4rs = "1.0.0"
tokio = { version = "1.11.0", features = ["rt-multi-thread", "macros", "net", "time"] }
failure = "0.1.8"
failure_derive = "0.1.8"
rocksdb = "0.17.0"
futures = "0.3.17"
tarpc = { version = "0.26.2", features = ["tokio1", "serde-transport", "tcp"] }
base64-url = "1.4.10"
serde_derive = "1.0.130"
serde = { version = "1.0.130", features = ["rc"] }
tokio-util = "0.6.8"
bytes = "1.1.0"
bincode = "1.3.3"
tokio-stream = { version = "0.1.7", features = ["net"] }
sha3 = "0.9.1"
warp = { version = "0.3.1", default-features = false }
getrandom = "0.2.3"
quinn = "0.7.2"
rustls = { version = "0.19.1", features = ["quic", "dangerous_configuration"] }
webpki = "0.21.4"
rcgen = "0.8.13"
chrono = { version = "0.4.19", features = ["serde"] }
rand = "^0.7"
rand_chacha = "0.2.2"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
aes-gcm-siv = "0.10.3"
