[package]
name = "samizdat-common"
version = "0.1.0"
authors = ["Pedro B Arruda <parruda@artmend.com.br>"]
edition = "2018"

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "0.8.3"
log = "0.4.14"
log4rs = "1.0.0"
tokio = { version = "1.3.0", features = ["rt-multi-thread", "macros", "net", "time"] }
failure = "0.1.8"
failure_derive = "0.1.8"
rocksdb = "0.15.0"
futures = "0.3.13"
tarpc = { version = "0.25.1", features = ["tokio1", "serde-transport", "tcp"] }
base64-url = "1.4.9"
serde_derive = "1.0.124"
serde = { version = "1.0.124", features = ["rc"] }
tokio-util = "0.6.4"
bytes = "1.0.1"
bincode = "1.3.2"
tokio-stream = { version = "0.1.4", features = ["net"] }
sha3 = "0.9.1"
warp = "0.3.0"
getrandom = "0.2.2"
