[package]
name = "samizdat-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64-url = "1.4.13"
bytes = "1.3.0"
failure = "0.1.8"
failure_derive = "0.1.8"
futures = "0.3.25"
http = "0.2.8"
lazy_static = "1.4.0"
log = "0.4.17"
log4rs = "1.2.0"
serde = "1.0.152"
serde_derive = "1.0.152"
structopt = "0.3.26"
tokio = { version = "1.23.0", features = ["rt-multi-thread", "macros", "net", "time"] }
warp = { version = "0.3.3", features = ["tls"] }
bincode = "1.3.3"
serde_json = "1.0.91"
askama = "0.11.1"
reqwest = { version = "0.11.13", default-features = false, features = ["rustls-tls", "stream"] }
hyper = "0.14.23"
mime = "0.3.16"
scraper = "0.14.0"
include_dir = "0.7.3"
static_dir = "0.2.0"
rand = "0.8.5"
