[package]
name = "samizdat-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64-url = "1.4.13"
bytes = "1.1.0"
failure = "0.1.8"
failure_derive = "0.1.8"
futures = "0.3.21"
http = "0.2.7"
lazy_static = "1.4.0"
log = "0.4.17"
log4rs = "1.1.1"
serde = "1.0.137"
serde_derive = "1.0.137"
structopt = "0.3.26"
tokio = { version = "1.18.1", features = ["rt-multi-thread", "macros", "net", "time"] }
warp = { version = "0.3.2", features = ["tls"] }
bincode = "1.3.3"
serde_json = "1.0.81"
askama = "0.11.1"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls"] }
hyper = "0.14.18"
mime = "0.3.16"
scraper = "0.13.0"
include_dir = "0.7.2"
static_dir = "0.2.0"
rand = "0.8.5"
