[package]
name = "samizdat-proxy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64-url = "1.4.10"
bytes = "1.0.1"
failure = "0.1.8"
failure_derive = "0.1.8"
futures = "0.3.16"
http = "0.2.4"
lazy_static = "1.4.0"
log = "0.4.14"
log4rs = "1.0.0"
serde = "1.0.127"
serde_derive = "1.0.127"
structopt = "0.3.22"
tokio = { version = "1.10.0", features = ["rt-multi-thread", "macros", "net", "time"] }
warp = "0.3.1"
bincode = "1.3.3"
serde_json = "1.0.66"
# samizdat-common = { path = "../common" }
askama = "0.10.5"
reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls"] }
hyper = "0.14.12"
mime = "0.3.16"
scraper = "0.12.0"
