project: samizdat-builder
root: src
output: dist

images:
  rust:
    path: ../..
    platform: linux/amd64
    dockerfile: install/src/images/Rust.dockerfile
  js:
    path: ../..
    dockerfile: install/src/images/Node.dockerfile

builders:
  js:
    image: js
    command: install/src/js/build.sh
  x86_64-unknown-linux-gnu:
    image: rust
    command: install/src/x86_64-unknown-linux-gnu/build.sh
  aarch64-apple-darwin:
    image: rust
    command: install/src/aarch64-apple-darwin/build.sh

exports:
  js:
    samizdat.js:
      from: js
      import: /build/js/dist/samizdat.js
  x86_64-unknown-linux-gnu:
    node:
      samizdat-node.service: ~
      install.sh:
        run: x86_64-unknown-linux-gnu/node/build-install.sh
      samizdat-node:
        from: x86_64-unknown-linux-gnu
        import: /build/target/x86_64-unknown-linux-gnu/release/samizdat-node
      samizdat:
        from: x86_64-unknown-linux-gnu
        import: /build/target/x86_64-unknown-linux-gnu/release/samizdat
    hub:
      samizdat-hub.service: ~
      install.sh:
        run: x86_64-unknown-linux-gnu/hub/build-install.sh
      samizdat-hub:
        from: x86_64-unknown-linux-gnu
        import: /build/target/x86_64-unknown-linux-gnu/release/samizdat-hub
  aarch64-apple-darwin:
    node:
      samizdat-node:
        from: aarch64-apple-darwin
        import: /build/target/aarch64-apple-darwin/release/samizdat-node
      samizdat:
        from: aarch64-apple-darwin
        import: /build/target/aarch64-apple-darwin/release/samizdat
