[package]
name = "samizdat-hub"
version = "0.1.0"
authors = ["Pedro B Arruda <parruda@artmend.com.br>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
log4rs = "1.0.0"
structopt = "0.3.26"
tokio = { version = "1.16.1", features = ["rt-multi-thread", "macros", "net", "time"] }
failure = "0.1.8"
failure_derive = "0.1.8"
rocksdb = { version = "0.18.0", default-features = false, features = [] }
futures = "0.3.21"
tarpc = { version = "0.27.2", features = ["tokio1", "serde-transport", "tcp"] }
lazy_static = "1.4.0"
base64-url = "1.4.10"
serde_derive = "1.0.136"
serde = { version = "1.0.136", features = ["rc"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
samizdat-common = { path = "../common"}
chashmap = "2.2.2"
quinn = "0.8.0"
bincode = "1.3.3"
chrono = "0.4.19"
rand = "0.7.3"
rand_distr = "0.3.0"
