[package]
name = "samizdat-hub"
version = "0.1.0"
authors = ["Pedro B Arruda <parruda@artmend.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "2.0.0"
log = "0.4.14"
log4rs = "1.0.0"
structopt = "0.3.22"
tokio = { version = "1.9.0", features = ["rt-multi-thread", "macros", "net", "time"] }
failure = "0.1.8"
failure_derive = "0.1.8"
rocksdb = "0.17.0"
futures = "0.3.16"
tarpc = { version = "0.26.2", features = ["tokio1", "serde-transport", "tcp"] }
lazy_static = "1.4.0"
base64-url = "1.4.10"
serde_derive = "1.0.127"
serde = { version = "1.0.127", features = ["rc"] }
tokio-stream = { version = "0.1.7", features = ["net"] }
samizdat-common = { path = "../common"}
chashmap = "2.2.2"
quinn = "0.7.2"
bincode = "1.3.3"
