[package]
name = "samizdat-hub"
version = "0.1.0"
authors = ["Pedro B Arruda <parruda@artmend.com.br>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
log4rs = "1.1.1"
structopt = "0.3.26"
tokio = { version = "1.18.1", features = ["rt-multi-thread", "macros", "net", "time"] }
failure = "0.1.8"
failure_derive = "0.1.8"
rocksdb = { version = "0.18.0", default-features = false, features = ["snappy"] }
futures = "0.3.21"
tarpc = { version = "0.28.0", features = ["tokio1", "serde-transport", "tcp"] }
lazy_static = "1.4.0"
base64-url = "1.4.13"
serde_derive = "1.0.137"
serde = { version = "1.0.137", features = ["rc"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
samizdat-common = { path = "../common"}
chashmap = "2.2.2"
quinn = "0.8.2"
bincode = "1.3.3"
chrono = "0.4.19"
rand = "0.7.0"
rand_distr = "0.3"
strum = "0.24.0"
strum_macros = "0.24.0"
warp = "0.3.2"
http = "0.2.7"
serde_json = "1.0.81"
