[package]
name = "samizdat-hub"
version = "0.1.0"
authors = ["Pedro B Arruda <parruda@artmend.com.br>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
log4rs = "1.2.0"
structopt = "0.3.26"
tokio = { version = "1.23.0", features = ["rt-multi-thread", "macros", "net", "time"] }
failure = "0.1.8"
failure_derive = "0.1.8"
rocksdb = { version = "0.19.0", default-features = false, features = ["snappy"] }
futures = "0.3.25"
tarpc = { version = "0.31.0", features = ["tokio1", "serde-transport", "tcp"] }
lazy_static = "1.4.0"
base64-url = "1.4.13"
serde_derive = "1.0.152"
serde = { version = "1.0.152", features = ["rc"] }
tokio-stream = { version = "0.1.11", features = ["net"] }
samizdat-common = { path = "../common"}
chashmap = "2.2.2"
quinn = "0.9.3" # do NOT upgrade until quinn bugfix!
bincode = "1.3.3"
chrono = "0.4.23"
rand = "0.8.5"
rand_distr = "0.4.3"
strum = "0.24.1"
strum_macros = "0.24.3"
warp = "0.3.3"
http = "0.2.8"
serde_json = "1.0.91"
