// automatically generated by the FlatBuffers compiler, do not modify



use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod object {

  use std::mem;
  use std::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum ObjectOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Object<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Object<'a> {
    type Inner = Object<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> Object<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Object { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args ObjectArgs<'args>) -> flatbuffers::WIPOffset<Object<'bldr>> {
      let mut builder = ObjectBuilder::new(_fbb);
      if let Some(x) = args.content { builder.add_content(x); }
      if let Some(x) = args.content_type { builder.add_content_type(x); }
      builder.finish()
    }

    pub const VT_CONTENT_TYPE: flatbuffers::VOffsetT = 4;
    pub const VT_CONTENT: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn content_type(&self) -> &'a str {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Object::VT_CONTENT_TYPE, None).unwrap()
  }
  #[inline]
  pub fn content(&self) -> &'a [u8] {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Object::VT_CONTENT, None).map(|v| v.safe_slice()).unwrap()
  }
}

impl flatbuffers::Verifiable for Object<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>(&"content_type", Self::VT_CONTENT_TYPE, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(&"content", Self::VT_CONTENT, true)?
     .finish();
    Ok(())
  }
}
pub struct ObjectArgs<'a> {
    pub content_type: Option<flatbuffers::WIPOffset<&'a str>>,
    pub content: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for ObjectArgs<'a> {
    #[inline]
    fn default() -> Self {
        ObjectArgs {
            content_type: None, // required field
            content: None, // required field
        }
    }
}
pub struct ObjectBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ObjectBuilder<'a, 'b> {
  #[inline]
  pub fn add_content_type(&mut self, content_type: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Object::VT_CONTENT_TYPE, content_type);
  }
  #[inline]
  pub fn add_content(&mut self, content: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Object::VT_CONTENT, content);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ObjectBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ObjectBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Object<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Object::VT_CONTENT_TYPE,"content_type");
    self.fbb_.required(o, Object::VT_CONTENT,"content");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl std::fmt::Debug for Object<'_> {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let mut ds = f.debug_struct("Object");
      ds.field("content_type", &self.content_type());
      ds.field("content", &self.content());
      ds.finish()
  }
}
#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_root_as_object<'a>(buf: &'a [u8]) -> Object<'a> {
  unsafe { flatbuffers::root_unchecked::<Object<'a>>(buf) }
}

#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_size_prefixed_root_as_object<'a>(buf: &'a [u8]) -> Object<'a> {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<Object<'a>>(buf) }
}

#[inline]
/// Verifies that a buffer of bytes contains a `Object`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_object_unchecked`.
pub fn root_as_object(buf: &[u8]) -> Result<Object, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Object>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Object` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_object_unchecked`.
pub fn size_prefixed_root_as_object(buf: &[u8]) -> Result<Object, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Object>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Object` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_object_unchecked`.
pub fn root_as_object_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Object<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Object<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Object` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_object_unchecked`.
pub fn size_prefixed_root_as_object_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Object<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Object<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Object and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Object`.
pub unsafe fn root_as_object_unchecked(buf: &[u8]) -> Object {
  flatbuffers::root_unchecked::<Object>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Object and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Object`.
pub unsafe fn size_prefixed_root_as_object_unchecked(buf: &[u8]) -> Object {
  flatbuffers::size_prefixed_root_unchecked::<Object>(buf)
}
#[inline]
pub fn finish_object_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<Object<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_object_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<Object<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Object

