name: Check

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-06-14
        default: true
        profile: minimal

    - name: Running cache
      uses: Swatinem/rust-cache@v1
      with:
        cache-on-failure: true
    
    - name: Running `cargo check`
      run: cargo check

    - name: Done
      run: echo Done
