name: Check

on:
  workflow_dispatch:


jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    
    - name: Setup virtualenv
      run: cd install && poetry lock
    
    - name: Run install builder
      run: cd install && poetry run python builder

    - name: Done
      run: echo Done
