name: Build

on:
  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install poetry
      run: pipx install poetry
    
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: poetry

    - name: Setup virtualenv
      run: cd install && poetry install
    
    - name: Run install builder
      run: cd install && poetry run python builder

    - name: Done
      run: echo Done
